### PR TITLE
Add elm-format 0.8.5

### PR DESCRIPTION
**Pull request by avh4**

### CODE REVIEW

**Comment by avh4** [comment]
I'm afraid I'm not understanding what this test is supposed to be checking or why it's failing.  And suggestions here?

```
 FAIL tests/getExecutable.test.ts
  ● getExecutable › already downloaded

    expect(received).resolves.toMatchInlineSnapshot()

    Received promise rejected instead of resolved
    Rejected to value: [Error: Expected onProgress not to be called]

      135 | 
      136 |   test("already downloaded", () =>
    > 137 |     expect(
          |     ^
      138 |       getExecutableHelper({
      139 |         fixture: "already-downloaded",
      140 |         name: "elm-format",

      at expect (node_modules/expect/build/index.js:134:15)
      at Object.<anonymous> (tests/getExecutable.test.ts:137:5)
```

**Comment by avh4** [comment]
Ah, I think I fixed it;  it seems that test is implicitly looking at the default version.

**Comment by lydell** [comment]
Looks like we sadly wrestled with the same trouble at the same time, then :(

https://github.com/elm-tooling/elm-tooling-cli/pull/32

**Comment by lydell** [comment]
Sorry, this bad test took up too much of my time. I’ll have to get back to this later today.

**Comment by avh4** [comment]
:+1:  FYI, I tried to make a script to automate the updates https://github.com/avh4/elm-format/pull/726/commits/a3c496bdfcebdf6956b5ef253f6a5f9e21801baf though there's still a bit of manual test fixing that has to be done

**Comment by lydell** [comment]
How come you don’t use `jest -u` to update all the snapshots?

The process is usually:

1. Add to known-tools.ts
2. `jest -u`
3. Fix one manual snapshots

**Comment by lydell** [comment]
I merged #32 in the end. I changed the test to require a specific (`=0.8.4`) version instead of a range, since it’s testing the case where the executable already exists on disk.

**Comment by avh4** [comment]
Great, thanks!

**Pull request closed without merging**
